// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcEJ6CkLohXeHml9CHf6BQuZhYdt-rnbs',
    appId: '1:240853229741:web:9b40c1795de92332592624',
    messagingSenderId: '240853229741',
    projectId: 'user-profile-management-app',
    authDomain: 'user-profile-management-app.firebaseapp.com',
    storageBucket: 'user-profile-management-app.firebasestorage.app',
    measurementId: 'G-C4W591K27B',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcEJ6CkLohXeHml9CHf6BQuZhYdt-rnbs',
    appId: '1:240853229741:web:7a66b5a4218a3e3b592624',
    messagingSenderId: '240853229741',
    projectId: 'user-profile-management-app',
    authDomain: 'user-profile-management-app.firebaseapp.com',
    storageBucket: 'user-profile-management-app.firebasestorage.app',
    measurementId: 'G-X2N17S7TJJ',
  );
}
